# Generated by Django 5.0 on 2023-12-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_last_name_alter_customuser_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
