# Generated by Django 5.0 on 2024-01-01 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50, unique=True)),
                ('year_of_manufacture', models.IntegerField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('total_km', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
