# Generated by Django 5.0 on 2024-01-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_uservehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservehicles',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uservehicles',
            name='vehicle',
            field=models.CharField(max_length=50),
        ),
    ]
