# Generated by Django 5.0 on 2024-01-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_uservehicles_brand_alter_uservehicles_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
