# Generated by Django 5.0 on 2024-01-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_mechanicprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicProfiledetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=10)),
                ('experience', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_pic', models.FileField(blank=True, null=True, upload_to='yourmechanic_userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
