# Generated by Django 5.0 on 2024-01-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_mechanicprofiledetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofiledetails',
            name='user',
        ),
        migrations.AddField(
            model_name='mechanicprofiledetails',
            name='mechanic_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
