# Generated by Django 5.0 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_mechanicprofiledetails_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofiledetails',
            name='is_verfiyed',
            field=models.BooleanField(default=False),
        ),
    ]
