# Generated by Django 5.0 on 2024-01-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_mechanicprofiledetails_is_verfiyed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mechanicprofiledetails',
            old_name='is_verfiyed',
            new_name='is_verifyed',
        ),
    ]
