# Generated by Django 5.0 on 2024-01-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_remove_mechanicprofiledetails_is_verifyed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofiledetails',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
