# Generated by Django 5.0 on 2024-01-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_mechanicprofiledetails_is_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date_time', models.DateTimeField(unique=True)),
                ('mechanic_id', models.IntegerField()),
                ('mechanic_name', models.CharField(max_length=100)),
                ('vehicle_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('service_id', models.IntegerField()),
            ],
        ),
    ]
