# Generated by Django 5.0 on 2024-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(),
        ),
    ]
