# Generated by Django 5.0 on 2024-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_booking_booking_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_time',
            field=models.DurationField(default='1:00:00'),
        ),
    ]
