# Generated by Django 5.0 on 2024-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_booking_service_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_time',
            field=models.DurationField(blank=True, default='1:00:00', null=True),
        ),
    ]
