# Generated by Django 5.0 on 2024-01-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofiledetails',
            name='mechanic_id',
            field=models.IntegerField(unique=True),
        ),
    ]
