# Generated by Django 5.0 on 2024-01-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_brand_vehicle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='name',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='name',
            new_name='vehicle_name',
        ),
    ]
