# Generated by Django 5.0 on 2024-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0002_rooms_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
