# Generated by Django 5.0 on 2024-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chatapp', '0003_rooms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='senderid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
