# Generated by Django 5.0 on 2024-01-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mechanic_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('payment', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('s', 'Scheduled'), ('p', 'Pending'), ('w', 'processing'), ('c', 'Completed')], default='p', max_length=1)),
            ],
        ),
    ]
