# Generated by Django 5.0 on 2024-01-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_bookings_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Scheduled'), ('w', 'ongoing'), ('c', 'Completed'), ('d', 'Canceld')], default='p', max_length=1),
        ),
    ]
