# Generated by Django 5.0 on 2024-01-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, verbose_name='payment id')),
                ('order_id', models.CharField(max_length=100, verbose_name='order id')),
                ('signature', models.CharField(max_length=200, verbose_name='signature')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
