# Generated by Django 5.0 on 2024-01-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_id',
            field=models.IntegerField(null=True),
        ),
    ]
