# Generated by Django 5.0 on 2024-01-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='datetime',
        ),
    ]
